# .travis.yml

language: node_js
node_js:
  - 11
cache: npm
notifications:
  email: false
git:
  depth: 3
branches:
  only:
    - master
script:
  - npm run lint
  - npm run test
  - npm run build -- --configuration production
